In [1]:
#Importação das bibliotecas -------------------------------------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
file_id_med = '1_oEoWVme6mKfqhl2Itlkb53u_EFz_u8s' 
url_med = f'https://drive.google.com/uc?export=download&id={file_id_med}'

file_id_paci = '1d-ZZjoFHCRym5tGei5cE05974uzPIuQT' 
url_paci = f'https://drive.google.com/uc?export=download&id={file_id_paci}'

file_id_cli = '14w0KYUbEJicByKS7M3upVvWzXKLH8kzQ' 
url_cli = f'https://drive.google.com/uc?export=download&id={file_id_cli}'

file_id_consul = '12bPlpo8oiaEOIuwQni1lKzc6fWKm7QfI' 
url_consul = f'https://drive.google.com/uc?export=download&id={file_id_consul}'

file_id_avali = '1X5cWJUBa712NGzpR5THEU1T4xlEozfoh' 
url_avali = f'https://drive.google.com/uc?export=download&id={file_id_avali}'

In [12]:
#importando todas as bases
df_med = pd.read_csv (url_med,sep=',', encoding='utf-8')
df_paci = pd.read_csv (url_paci,sep=',', encoding='utf-8')
df_cli = pd.read_csv (url_cli,sep=',', encoding='utf-8')
df_consul = pd.read_csv (url_consul,sep=',', encoding='utf-8')
df_avali = pd.read_csv (url_avali,sep=',', encoding='utf-8')

In [4]:
# Criando uma lista pra facilitar o concat
lista = [df_med,df_paci,df_cli,df_consul,df_avali]

In [17]:
df_consul

,id_consulta,id_paciente,id_medico,id_clinica,especialidade,data_hora_agendada,data_hora_inicio,status
0,1,82,15,4,Cardiologia,2023-09-27 23:46,2023-09-28 00:16,Realizada
1,2,18,95,14,Cardiologia,2023-09-04 09:05,2023-09-04 13:05,Realizada
2,3,55,5,4,Pediatria,2023-02-04 02:43,2023-02-04 02:58,Realizada
3,4,78,4,72,Ortopedia,2023-03-14 09:28,2023-03-14 13:28,Realizada
4,5,58,76,36,Pediatria,2023-10-22 16:54,2023-10-22 16:54,Cancelada
...,...,...,...,...,...,...,...,...
4995,4996,27,27,93,Pediatria,2023-03-28 04:34,2023-03-28 05:34,Cancelada
4996,4997,17,26,8,Cardiologia,2023-12-06 12:39,2023-12-06 12:54,Realizada
4997,4998,60,39,34,Ortopedia,2023-11-06 11:27,2023-11-06 11:27,Realizada
4998,4999,65,7,98,Dermatologia,2023-10-07 20:19,2023-10-07 22:19,Realizada
4999,5000,65,93,78,Cardiologia,2023-07-23 07:16,2023-07-23 10:16,Remarcada

In [18]:
# Converte para datetime
df_consul["data_hora_agendada"] = pd.to_datetime(df_consul["data_hora_agendada"], errors="coerce", dayfirst=True)  # ajusta dayfirst conforme seu formato

# Separa data e hora
df_consul['data_agendada'] = df_consul['data_hora_agendada'].dt.date   # Apenas a data
df_consul['hora_agendada'] = df_consul['data_hora_agendada'].dt.time    # Apenas a hora

df_consul

C:\Users\biblioteca.sl\AppData\Local\Temp\ipykernel_14356\3882137774.py:2: UserWarning: Parsing dates in %Y-%m-%d %H:%M format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_consul["data_hora_agendada"] = pd.to_datetime(df_consul["data_hora_agendada"], errors="coerce", dayfirst=True)  # ajusta dayfirst conforme seu formato

,id_consulta,id_paciente,id_medico,id_clinica,especialidade,data_hora_agendada,data_hora_inicio,status,data_agendada,hora_agendada
0,1,82,15,4,Cardiologia,2023-09-27 23:46:00,2023-09-28 00:16,Realizada,2023-09-27,23:46:00
1,2,18,95,14,Cardiologia,2023-09-04 09:05:00,2023-09-04 13:05,Realizada,2023-09-04,09:05:00
2,3,55,5,4,Pediatria,2023-02-04 02:43:00,2023-02-04 02:58,Realizada,2023-02-04,02:43:00
3,4,78,4,72,Ortopedia,2023-03-14 09:28:00,2023-03-14 13:28,Realizada,2023-03-14,09:28:00
4,5,58,76,36,Pediatria,2023-10-22 16:54:00,2023-10-22 16:54,Cancelada,2023-10-22,16:54:00
...,...,...,...,...,...,...,...,...,...,...
4995,4996,27,27,93,Pediatria,2023-03-28 04:34:00,2023-03-28 05:34,Cancelada,2023-03-28,04:34:00
4996,4997,17,26,8,Cardiologia,2023-12-06 12:39:00,2023-12-06 12:54,Realizada,2023-12-06,12:39:00
4997,4998,60,39,34,Ortopedia,2023-11-06 11:27:00,2023-11-06 11:27,Realizada,2023-11-06,11:27:00
4998,4999,65,7,98,Dermatologia,2023-10-07 20:19:00,2023-10-07 22:19,Realizada,2023-10-07,20:19:00
4999,5000,65,93,78,Cardiologia,2023-07-23 07:16:00,2023-07-23 10:16,Remarcada,2023-07-23,07:16:00

In [19]:
# Converte para datetime
df_consul["data_hora_inicio"] = pd.to_datetime(df_consul["data_hora_inicio"], errors="coerce", dayfirst=True)  # ajusta dayfirst conforme seu formato


# Separa data e hora
df_consul['data_inicio'] = df_consul['data_hora_inicio'].dt.date   # Apenas a data
df_consul['hora_inicio'] = df_consul['data_hora_inicio'].dt.time    # Apenas a hora

df_consul

C:\Users\biblioteca.sl\AppData\Local\Temp\ipykernel_14356\364841044.py:2: UserWarning: Parsing dates in %Y-%m-%d %H:%M format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_consul["data_hora_inicio"] = pd.to_datetime(df_consul["data_hora_inicio"], errors="coerce", dayfirst=True)  # ajusta dayfirst conforme seu formato

,id_consulta,id_paciente,id_medico,id_clinica,especialidade,data_hora_agendada,data_hora_inicio,status,data_agendada,hora_agendada,data_inicio,hora_inicio
0,1,82,15,4,Cardiologia,2023-09-27 23:46:00,2023-09-28 00:16:00,Realizada,2023-09-27,23:46:00,2023-09-28,00:16:00
1,2,18,95,14,Cardiologia,2023-09-04 09:05:00,2023-09-04 13:05:00,Realizada,2023-09-04,09:05:00,2023-09-04,13:05:00
2,3,55,5,4,Pediatria,2023-02-04 02:43:00,2023-02-04 02:58:00,Realizada,2023-02-04,02:43:00,2023-02-04,02:58:00
3,4,78,4,72,Ortopedia,2023-03-14 09:28:00,2023-03-14 13:28:00,Realizada,2023-03-14,09:28:00,2023-03-14,13:28:00
4,5,58,76,36,Pediatria,2023-10-22 16:54:00,2023-10-22 16:54:00,Cancelada,2023-10-22,16:54:00,2023-10-22,16:54:00
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,27,27,93,Pediatria,2023-03-28 04:34:00,2023-03-28 05:34:00,Cancelada,2023-03-28,04:34:00,2023-03-28,05:34:00
4996,4997,17,26,8,Cardiologia,2023-12-06 12:39:00,2023-12-06 12:54:00,Realizada,2023-12-06,12:39:00,2023-12-06,12:54:00
4997,4998,60,39,34,Ortopedia,2023-11-06 11:27:00,2023-11-06 11:27:00,Realizada,2023-11-06,11:27:00,2023-11-06,11:27:00
4998,4999,65,7,98,Dermatologia,2023-10-07 20:19:00,2023-10-07 22:19:00,Realizada,2023-10-07,20:19:00,2023-10-07,22:19:00
4999,5000,65,93,78,Cardiologia,2023-07-23 07:16:00,2023-07-23 10:16:00,Remarcada,2023-07-23,07:16:00,2023-07-23,10:16:00