In [31]:
#Importação das bibliotecas -------------------------------------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [36]:
file_id_med = '1tu0E4Xqt7FeprldGQYI4uypcncIOwDHl' 
url_med = f'https://drive.google.com/uc?export=download&id={file_id_med}'

file_id_paci = '1d-ZZjoFHCRym5tGei5cE05974uzPIuQT' 
url_paci = f'https://drive.google.com/uc?export=download&id={file_id_paci}'

file_id_cli = '14w0KYUbEJicByKS7M3upVvWzXKLH8kzQ' 
url_cli = f'https://drive.google.com/uc?export=download&id={file_id_cli}'

file_id_consul = '12bPlpo8oiaEOIuwQni1lKzc6fWKm7QfI' 
url_consul = f'https://drive.google.com/uc?export=download&id={file_id_consul}'

file_id_avali = '1X5cWJUBa712NGzpR5THEU1T4xlEozfoh' 
url_avali = f'https://drive.google.com/uc?export=download&id={file_id_avali}'

In [40]:
#importando todas as bases
df_med = pd.read_csv (url_med,sep=';', encoding='utf-8')
df_paci = pd.read_csv (url_paci,sep=',', encoding='utf-8')
df_cli = pd.read_csv (url_cli,sep=',', encoding='utf-8')
df_consul = pd.read_csv (url_consul,sep=',', encoding='utf-8')
df_avali = pd.read_csv (url_avali,sep=',', encoding='utf-8')

In [38]:
# Criando uma lista pra facilitar o concat
lista = [df_med,df_paci,df_cli,df_consul,df_avali]

In [41]:
df_med

    id_medico                       nome   especialidade
0           1      Dr(a). Fernanda Gomes      Neurologia
1           2       Dr(a). Ricardo Souza    Oftalmologia
2           3    Dr(a). Juliana Oliveira      Neurologia
3           4  Dr(a). Mariana Nascimento    Oftalmologia
4           5     Dr(a). Mariana Almeida       Pediatria
..        ...                        ...             ...
95         96   Dr(a). Camila Nascimento        Urologia
96         97         Dr(a). André Gomes  Endocrinologia
97         98     Dr(a). Mariana Almeida       Pediatria
98         99       Dr(a). Eduardo Souza      Neurologia
99        100  Dr(a). Mariana Nascimento      Neurologia

[100 rows x 3 columns]

In [ ]:
# Filtra somente as consultas realizadas
df_realizadas= df_consul.loc[df_consul['status'] == 'Realizada']

In [ ]:
# Converte para datetime
df_realizadas["data_hora_agendada"] = pd.to_datetime(df_realizadas["data_hora_agendada"], errors="coerce", dayfirst=True)  
df_realizadas["data_hora_inicio"] = pd.to_datetime(df_realizadas["data_hora_inicio"], errors="coerce", dayfirst=True)

C:\Users\36134552025.1\AppData\Local\Temp\ipykernel_4872\111831289.py:2: UserWarning: Parsing dates in %Y-%m-%d %H:%M format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_realizadas["data_hora_agendada"] = pd.to_datetime(df_realizadas["data_hora_agendada"], errors="coerce", dayfirst=True)
C:\Users\36134552025.1\AppData\Local\Temp\ipykernel_4872\111831289.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_realizadas["data_hora_agendada"] = pd.to_datetime(df_realizadas["data_hora_agendada"], errors="coerce", dayfirst=True)
C:\Users\36134552025.1\AppData\Local\Temp\ipykernel_4872\111831289.py:3: UserWarning: Parsing dates in %Y-%m-%d %H:%M format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_realizadas["data_hora_inicio"] = pd.to_datetime(df_realizadas["data_hora_inicio"], errors="coerce", dayfirst=True)
C:\Users\36134552025.1\AppData\Local\Temp\ipykernel_4872\111831289.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_realizadas["data_hora_inicio"] = pd.to_datetime(df_realizadas["data_hora_inicio"], errors="coerce", dayfirst=True)

In [ ]:
# Criar uma coluna para tempo de espera e fazer o calculo da espera em minuto
df_realizadas['tempo_espera_min'] = ((df_realizadas['data_hora_inicio'] - df_realizadas['data_hora_agendada']).dt.total_seconds() / 60)
df_realizadas

C:\Users\36134552025.1\AppData\Local\Temp\ipykernel_4872\4209809687.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_realizadas['tempo_espera_min'] = ((df_realizadas['data_hora_inicio'] - df_realizadas['data_hora_agendada']).dt.total_seconds() / 60)

,id_consulta,id_paciente,id_medico,id_clinica,especialidade,data_hora_agendada,data_hora_inicio,status,tempo_espera_min
0,1,82,15,4,Cardiologia,2023-09-27 23:46:00,2023-09-28 00:16:00,Realizada,30.0
1,2,18,95,14,Cardiologia,2023-09-04 09:05:00,2023-09-04 13:05:00,Realizada,240.0
2,3,55,5,4,Pediatria,2023-02-04 02:43:00,2023-02-04 02:58:00,Realizada,15.0
3,4,78,4,72,Ortopedia,2023-03-14 09:28:00,2023-03-14 13:28:00,Realizada,240.0
5,6,21,90,55,Dermatologia,2023-05-04 21:09:00,2023-05-04 21:39:00,Realizada,30.0
...,...,...,...,...,...,...,...,...,...
4992,4993,89,96,3,Neurologia,2023-08-29 07:47:00,2023-08-29 10:47:00,Realizada,180.0
4993,4994,2,20,51,Dermatologia,2023-04-28 03:01:00,2023-04-28 03:11:00,Realizada,10.0
4996,4997,17,26,8,Cardiologia,2023-12-06 12:39:00,2023-12-06 12:54:00,Realizada,15.0
4997,4998,60,39,34,Ortopedia,2023-11-06 11:27:00,2023-11-06 11:27:00,Realizada,0.0
4998,4999,65,7,98,Dermatologia,2023-10-07 20:19:00,2023-10-07 22:19:00,Realizada,120.0

In [ ]:
df_= df_realizadas.groupby(['especialidade'])['tempo_espera_min'].sum().reset_index()
df_

  especialidade  tempo_espera_min
0   Cardiologia           71145.0
1  Dermatologia           34295.0
2   Ginecologia           54540.0
3    Neurologia           28750.0
4     Ortopedia           71750.0
5     Pediatria           70325.0

In [ ]:
# Cardiologia
# Filtra somente cardiologia
df_cardio= df_realizadas.loc[df_consul['especialidade'] == 'Cardiologia']

#array
array_cardio= df_cardio['tempo_espera_min']
dados_cardio= np.array(array_cardio)

#média 
media_cardio= np.mean(dados_cardio)

#mediana 
mediana_cardio= np.median(dados_cardio)

#distancia 
distancia_cardio= (media_cardio - mediana_cardio) / mediana_cardio *100

print(f"Média: {media_cardio}\nMediana: {mediana_cardio}\nDistancia: {distancia_cardio}")

Média: 93.61184210526316
Mediana: 45.0
Distancia: 108.0263157894737

In [ ]:
# Dermatologia ___________________________________________________________________________________________________________
# Filtra somente cardiologia
df_dermatologia= df_realizadas.loc[df_consul['especialidade'] == 'Dermatologia']

#array
array_dermatologia= df_dermatologia['tempo_espera_min']
dados_dermatologia= np.array(array_dermatologia)

#média 
media_dermatologia= np.mean(dados_dermatologia)
media_dermatologia

#mediana 
mediana_dermatologia= np.median(dados_dermatologia)
mediana_dermatologia

#distancia 
distancia_dermatologia= (media_dermatologia - mediana_dermatologia) / mediana_dermatologia *100
distancia_dermatologia

print(f"Média: {media_dermatologia}\nMediana: {mediana_dermatologia}\nDistancia: {distancia_dermatologia}")

Média: 98.54885057471265
Mediana: 60.0
Distancia: 64.24808429118775

In [ ]:
# Ginecologia ___________________________________________________________________________________________________________
# Filtra somente cardiologia
df_ginecologia= df_realizadas.loc[df_consul['especialidade'] == 'Ginecologia']

#array
array_ginecologia= df_ginecologia['tempo_espera_min']
dados_ginecologia= np.array(array_ginecologia)

#média 
media_ginecologia= np.mean(dados_ginecologia)
media_ginecologia

#mediana 
mediana_ginecologia= np.median(dados_ginecologia)
mediana_ginecologia

#distancia 
distancia_ginecologia= (media_ginecologia - mediana_ginecologia) / mediana_ginecologia *100
distancia_ginecologia

print(f"Média: {media_ginecologia}\nMediana: {mediana_ginecologia}\nDistancia: {distancia_ginecologia}")

Média: 95.01742160278745
Mediana: 30.0
Distancia: 216.72473867595818

In [ ]:
# Neurologia ___________________________________________________________________________________________________________
# Filtra somente cardiologia
df_neurologia= df_realizadas.loc[df_consul['especialidade'] == 'Neurologia']

#array
array_neurologia= df_neurologia['tempo_espera_min']
dados_neurologia= np.array(array_neurologia)

#média 
media_neurologia= np.mean(dados_neurologia)
media_neurologia

#mediana 
mediana_neurologia= np.median(dados_neurologia)
mediana_neurologia

#distancia 
distancia_neurologia= (media_neurologia - mediana_neurologia) / mediana_neurologia *100
distancia_neurologia

print(f"Média: {media_neurologia}\nMediana: {mediana_neurologia}\nDistancia: {distancia_neurologia}")

Média: 95.19867549668874
Mediana: 60.0
Distancia: 58.664459161147896

In [ ]:
# Ortopedia ___________________________________________________________________________________________________________
# Filtra somente cardiologia
df_ortopedia= df_realizadas.loc[df_consul['especialidade'] == 'Ortopedia']

#array
array_ortopedia= df_ortopedia['tempo_espera_min']
dados_ortopedia= np.array(array_ortopedia)

#média 
media_ortopedia= np.mean(dados_ortopedia)
media_ortopedia

#mediana 
mediana_ortopedia= np.median(dados_ortopedia)
mediana_ortopedia

#distancia 
distancia_ortopedia= (media_ortopedia - mediana_ortopedia) / mediana_ortopedia *100
distancia_ortopedia

print(f"Média: {media_ortopedia}\nMediana: {mediana_ortopedia}\nDistancia: {distancia_ortopedia}")

Média: 94.65699208443272
Mediana: 30.0
Distancia: 215.52330694810905

In [ ]:
# Pediatria ___________________________________________________________________________________________________________
# Filtra somente cardiologia
df_pediatria= df_realizadas.loc[df_consul['especialidade'] == 'Pediatria']

#array
array_pediatria= df_pediatria['tempo_espera_min']
dados_pediatria= np.array(array_pediatria)

#média 
media_pediatria= np.mean(dados_pediatria)
media_pediatria

#mediana 
mediana_pediatria= np.median(dados_pediatria)
mediana_pediatria

#distancia 
distancia_pediatria= (media_pediatria - mediana_pediatria) / mediana_pediatria *100
distancia_pediatria

print(f"Média: {media_pediatria}\nMediana: {mediana_pediatria}\nDistancia: {distancia_pediatria}")

Média: 98.08228730822873
Mediana: 30.0
Distancia: 226.94095769409577

In [ ]:
df_med

,id_medico,nome,especialidade,tempo_medio_atendimento
0,1,Dr(a). Fernanda Gomes,Neurologia,35
1,2,Dr(a). Ricardo Souza,Oftalmologia,39
2,3,Dr(a). Juliana Oliveira,Neurologia,34
3,4,Dr(a). Mariana Nascimento,Oftalmologia,18
4,5,Dr(a). Mariana Almeida,Pediatria,39
...,...,...,...,...
95,96,Dr(a). Camila Nascimento,Urologia,28
96,97,Dr(a). André Gomes,Endocrinologia,18
97,98,Dr(a). Mariana Almeida,Pediatria,24
98,99,Dr(a). Eduardo Souza,Neurologia,34
99,100,Dr(a). Mariana Nascimento,Neurologia,46

In [ ]:
df_m= df_med.groupby(['nome'])['tempo_medio_atendimento'].sum().reset_index()
df_m

                          nome  tempo_medio_atendimento
0         Dr(a). André Almeida                       75
1           Dr(a). André Gomes                       73
2            Dr(a). André Lima                       79
3      Dr(a). André Nascimento                       55
4        Dr(a). André Oliveira                      104
5         Dr(a). André Pereira                       28
6           Dr(a). André Souza                       17
7        Dr(a). Camila Almeida                       87
8          Dr(a). Camila Costa                      109
9          Dr(a). Camila Gomes                       53
10          Dr(a). Camila Lima                       87
11    Dr(a). Camila Nascimento                       28
12     Dr(a). Camila Rodrigues                       52
13         Dr(a). Camila Silva                       50
14         Dr(a). Camila Souza                       52
15         Dr(a). Carlos Costa                       51
16         Dr(a). Carlos Gomes                       29
17          Dr(a). Carlos Lima                       93
18    Dr(a). Carlos Nascimento                       40
19      Dr(a). Carlos Oliveira                       32
20       Dr(a). Carlos Pereira                       49
21        Dr(a). Eduardo Costa                       25
22        Dr(a). Eduardo Gomes                       47
23         Dr(a). Eduardo Lima                      159
24   Dr(a). Eduardo Nascimento                       29
25    Dr(a). Eduardo Rodrigues                       36
26        Dr(a). Eduardo Souza                       34
27     Dr(a). Fernanda Almeida                       59
28       Dr(a). Fernanda Costa                       17
29       Dr(a). Fernanda Gomes                       35
30    Dr(a). Fernanda Oliveira                       60
31     Dr(a). Fernanda Pereira                       74
32   Dr(a). Fernanda Rodrigues                       55
33       Dr(a). Fernanda Souza                       49
34           Dr(a). João Costa                       20
35           Dr(a). João Gomes                      151
36       Dr(a). João Rodrigues                       38
37        Dr(a). Juliana Costa                       45
38     Dr(a). Juliana Oliveira                      109
39      Dr(a). Juliana Pereira                       83
40      Dr(a). Mariana Almeida                      194
41        Dr(a). Mariana Costa                       55
42         Dr(a). Mariana Lima                       69
43   Dr(a). Mariana Nascimento                      124
44     Dr(a). Mariana Oliveira                       60
45        Dr(a). Mariana Silva                       72
46     Dr(a). Patrícia Almeida                       77
47       Dr(a). Patrícia Gomes                       75
48        Dr(a). Patrícia Lima                       92
49  Dr(a). Patrícia Nascimento                       45
50    Dr(a). Patrícia Oliveira                       43
51     Dr(a). Patrícia Pereira                       57
52       Dr(a). Patrícia Souza                      150
53      Dr(a). Ricardo Almeida                       73
54        Dr(a). Ricardo Costa                       56
55         Dr(a). Ricardo Lima                       54
56   Dr(a). Ricardo Nascimento                       16
57        Dr(a). Ricardo Silva                       88
58        Dr(a). Ricardo Souza                       39

In [ ]:

dfs_por_medico = {}

for id_med in df_med['med'].unique():
    df_medico = df_med[df_med['nome'] == id_med]
    
    if df_medico.empty:
        continue
    
    medico_info = df_med[df_med['nome'] == id_med].iloc[0]
    nome = medico_info['nome']

      
    nome_formatado = nome.strip().replace(' ', '_').replace('á', 'a').replace('é', 'e') \
                                  .replace('í', 'i').replace('ó', 'o').replace('ú', 'u') \
                                  .replace('ç', 'c').replace('ã', 'a').replace('õ', 'o')
    
    
    dfs_por_medico[nome_formatado] = df_med

    #array
    array_pediatria= df_pediatria['tempo_medio_atendimento']
    dados_pediatria= np.array(array_pediatria)

    #média, mediana e distância
    media_pediatria= np.mean(dados_pediatria)
    media_pediatria

    mediana_pediatria= np.median(dados_pediatria)
    mediana_pediatria

    distancia_pediatria= (media_pediatria - mediana_pediatria) / mediana_pediatria *100
    distancia_pediatria

    #quartil
    q1_pediatria= np.percentile(dados_pediatria, 25)
    q2_pediatria= np.percentile(dados_pediatria, 50)
    q3_pediatria= np.percentile(dados_pediatria, 75)

    #Intervalo de interquartil
    IQR= q3_pediatria - q1_pediatria

    #limite superior e inferior
    ls_pediatria= q3_pediatria + (1.5 * IQR)
    li_pediatria= q1_pediatria - (1.5 * IQR)

KeyError: 'med'